AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Quick and dirty demo that calls AWS Bedrock via a Lambda function
Globals:
  Function:
    Timeout: 3

Resources:
  BedrockDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bedrock_demo/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        BedrockDemo:
          Type: Api
          Properties:
            Path: /bedrock-demo
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BedrockDemoApi:
    Description: "API Gateway endpoint URL for Prod stage for Bedrock Demo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bedrock-demo/"
  BedrockDemoFunction:
    Description: "Bedrock Demo Lambda Function ARN"
    Value: !GetAtt BedrockDemoFunction.Arn
  BedrockDemoFunctionIamRole:
    Description: "Implicit IAM Role created for Bedrock Demo function"
    Value: !GetAtt BedrockDemoFunctionRole.Arn
